
# Why:
# training with only lmk loss for good initialization,
# because the use of photometric loss needs good initialization both in regression and optimization
# and also, photometric loss needs differentiable rendering that makes the training slow
#
#
output_dir: "work_dir/DECA_RNNwithBN_tmp"
# pretrained_modelpath: "/content/drive/MyDrive/Colab_Notebooks/NewDECA/Detail/"
pretrained_modelpath: " " # "work_dir/DECA_RNNwithBN1/models/00050000.tar"  #
dataset:
  batch_size: 2
  K: 5
loss:
  photo: 0.
  id: 0.
  useSeg: False
  reg_tex: 0.
  reg_light: 0.
  shape_consistency: False
train:
  resume: True
  max_epochs: 10000
  max_steps: 100000
  log_steps: 10
  vis_steps: 100
  checkpoint_steps: 100
  val_steps: 100
  eval_steps: 1000
