
# why:
# pretrained_modelpath: '/ps/scratch/yfeng/Data/Projects-data/DECA-training/training/DECA_SIGGRAPH/pretrain/model.tar'
output_dir: "work_dir/DECA_RNNwithBN_tmp4w_Coarse6900_detail_maxz001_tmp"
# pretrained_modelpath: "/content/drive/MyDrive/Colab_Notebooks/NewDECA/Coarse/model.tar"
pretrained_modelpath:  "work_dir/DECA_RNNwithBN_tmp4w_Coarse6900_detail_maxz0001/models/00010800.tar"  #"work_dir/DECA_RNNwithBN_tmp4w_Coarse/models/00006900.tar"  #"work_dir/DECA_RNNwithBN_Coarse/models/00000200.tar"
dataset:
  batch_size: 2
  K: 5
train:
  train_detail: True
  resume: True
  max_epochs: 1000
  max_steps: 1000000
  log_steps: 10
  vis_steps: 10
  checkpoint_steps: 100
  val_steps: 500
  eval_steps: 1000
dataset:
  training_data: ['vggface2']
# python main_train_deca_release.py --cfg configs/release_version/deca_coarse.yml
