# Time:
# around 15min/1000iterations
# in total, needs around
output_dir: "work_dir/DECA_RNNwithBN_tmp4w_Coarse"
pretrained_modelpath: "work_dir/DECA_RNNwithBN_tmp/models/00040000.tar"
dataset:
  batch_size: 2
  K: 5
train:
  resume: True
  max_epochs: 1000
  max_steps: 100000
  log_steps: 20
  vis_steps: 100
  checkpoint_steps: 100
  val_steps: 500
  eval_steps: 1000

# python main_train_deca_release.py --cfg configs/release_version/deca_coarse.yml
